pipeline {
  agent any

  stages {
    stage('Start Infra (LocalStack + Kafka)') {
      steps {
        // Ensure network exists
        sh 'docker network inspect store-net || docker network create store-net'

        // Start infra dependencies only (not the app services yet)
        sh 'docker compose up localstack zookeeper kafka kafka-ui'

        // Give LocalStack time to start
        sh 'sleep 30'
      }
    }

    stage('Deploy AWS Resources (CloudFormation)') {
      steps {
        dir('infra') {
          sh 'chmod +x infra-bootstrap.sh'
          sh './infra-bootstrap.sh'
        }
      }
    }

    stage('Deploy Application Containers') {
      steps {
        // This starts kafka-app and rest-api services
        sh 'docker compose up --build kafka-app app'
      }
    }
  }
}
