server:
  port : 8082
spring:
#  datasource:
#    url: jdbc:postgresql://postgres:5432/store
#    username: user
#    password: password
#    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always         # Enables execution of data.sql
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update     # or "create" if you want tables dropped and re-created
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

localstack:
  aws:
    region: us-east-1
    s3:
      endpoint-url: http://localstack:4566
      access-key: test
      secret-key: test
    secrets-manager:
      endpoint-url: http://localstack:4566


product:
  service:
    url: http://app:8080
